version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: postgres
    volumes:
      - ./init_schema.sql:/docker-entrypoint-initdb.d/init.sql
  service:
    build: .
    image: app_django
    restart: always
    volumes:
      - ./static:/opt/app/movies_app/static/
      - ./media:/opt/app/movies_app/media/
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./movies_app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./movies_app/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./static:/app/static/
      - ./media:/app/media/
    depends_on:
      - service
    ports:
      - "80:80"
