version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: postgres
    ports:
      - "5432:5432"
  service:
    image: app_django
    restart: always
    depends_on:
      - postgres
      - migration
    ports:
      - "8000:8000"
  migration:
    build: app
    image: app_django
    entrypoint: python manage.py migrate --noinput
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./app/static:/app/static/:ro
      - ./app/media:/app/media/:ro
    depends_on:
      - service
    ports:
      - "80:80"
